// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ONSdigital/blaise-cawi-portal/authenticate"
	"github.com/gin-contrib/sessions"
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthInterface creates a new instance of AuthInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthInterface {
	mock := &AuthInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthInterface is an autogenerated mock type for the AuthInterface type
type AuthInterface struct {
	mock.Mock
}

type AuthInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthInterface) EXPECT() *AuthInterface_Expecter {
	return &AuthInterface_Expecter{mock: &_m.Mock}
}

// AuthenticatedWithUAC provides a mock function for the type AuthInterface
func (_mock *AuthInterface) AuthenticatedWithUAC(context *gin.Context) {
	_mock.Called(context)
	return
}

// AuthInterface_AuthenticatedWithUAC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticatedWithUAC'
type AuthInterface_AuthenticatedWithUAC_Call struct {
	*mock.Call
}

// AuthenticatedWithUAC is a helper method to define mock.On call
//   - context *gin.Context
func (_e *AuthInterface_Expecter) AuthenticatedWithUAC(context any) *AuthInterface_AuthenticatedWithUAC_Call {
	return &AuthInterface_AuthenticatedWithUAC_Call{Call: _e.mock.On("AuthenticatedWithUAC", context)}
}

func (_c *AuthInterface_AuthenticatedWithUAC_Call) Run(run func(context *gin.Context)) *AuthInterface_AuthenticatedWithUAC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthInterface_AuthenticatedWithUAC_Call) Return() *AuthInterface_AuthenticatedWithUAC_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthInterface_AuthenticatedWithUAC_Call) RunAndReturn(run func(context *gin.Context)) *AuthInterface_AuthenticatedWithUAC_Call {
	_c.Run(run)
	return _c
}

// HasSession provides a mock function for the type AuthInterface
func (_mock *AuthInterface) HasSession(context *gin.Context) (bool, *authenticate.UACClaims) {
	ret := _mock.Called(context)

	if len(ret) == 0 {
		panic("no return value specified for HasSession")
	}

	var r0 bool
	var r1 *authenticate.UACClaims
	if returnFunc, ok := ret.Get(0).(func(*gin.Context) (bool, *authenticate.UACClaims)); ok {
		return returnFunc(context)
	}
	if returnFunc, ok := ret.Get(0).(func(*gin.Context) bool); ok {
		r0 = returnFunc(context)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(*gin.Context) *authenticate.UACClaims); ok {
		r1 = returnFunc(context)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*authenticate.UACClaims)
		}
	}
	return r0, r1
}

// AuthInterface_HasSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasSession'
type AuthInterface_HasSession_Call struct {
	*mock.Call
}

// HasSession is a helper method to define mock.On call
//   - context *gin.Context
func (_e *AuthInterface_Expecter) HasSession(context any) *AuthInterface_HasSession_Call {
	return &AuthInterface_HasSession_Call{Call: _e.mock.On("HasSession", context)}
}

func (_c *AuthInterface_HasSession_Call) Run(run func(context *gin.Context)) *AuthInterface_HasSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthInterface_HasSession_Call) Return(b bool, uACClaims *authenticate.UACClaims) *AuthInterface_HasSession_Call {
	_c.Call.Return(b, uACClaims)
	return _c
}

func (_c *AuthInterface_HasSession_Call) RunAndReturn(run func(context *gin.Context) (bool, *authenticate.UACClaims)) *AuthInterface_HasSession_Call {
	_c.Call.Return(run)
	return _c
}

// IsUAC16 provides a mock function for the type AuthInterface
func (_mock *AuthInterface) IsUAC16() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsUAC16")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// AuthInterface_IsUAC16_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUAC16'
type AuthInterface_IsUAC16_Call struct {
	*mock.Call
}

// IsUAC16 is a helper method to define mock.On call
func (_e *AuthInterface_Expecter) IsUAC16() *AuthInterface_IsUAC16_Call {
	return &AuthInterface_IsUAC16_Call{Call: _e.mock.On("IsUAC16")}
}

func (_c *AuthInterface_IsUAC16_Call) Run(run func()) *AuthInterface_IsUAC16_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthInterface_IsUAC16_Call) Return(b bool) *AuthInterface_IsUAC16_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *AuthInterface_IsUAC16_Call) RunAndReturn(run func() bool) *AuthInterface_IsUAC16_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type AuthInterface
func (_mock *AuthInterface) Login(context *gin.Context, session sessions.Session) {
	_mock.Called(context, session)
	return
}

// AuthInterface_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthInterface_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - context *gin.Context
//   - session sessions.Session
func (_e *AuthInterface_Expecter) Login(context any, session any) *AuthInterface_Login_Call {
	return &AuthInterface_Login_Call{Call: _e.mock.On("Login", context, session)}
}

func (_c *AuthInterface_Login_Call) Run(run func(context *gin.Context, session sessions.Session)) *AuthInterface_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		var arg1 sessions.Session
		if args[1] != nil {
			arg1 = args[1].(sessions.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthInterface_Login_Call) Return() *AuthInterface_Login_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthInterface_Login_Call) RunAndReturn(run func(context *gin.Context, session sessions.Session)) *AuthInterface_Login_Call {
	_c.Run(run)
	return _c
}

// Logout provides a mock function for the type AuthInterface
func (_mock *AuthInterface) Logout(context *gin.Context, session sessions.Session) {
	_mock.Called(context, session)
	return
}

// AuthInterface_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthInterface_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - context *gin.Context
//   - session sessions.Session
func (_e *AuthInterface_Expecter) Logout(context any, session any) *AuthInterface_Logout_Call {
	return &AuthInterface_Logout_Call{Call: _e.mock.On("Logout", context, session)}
}

func (_c *AuthInterface_Logout_Call) Run(run func(context *gin.Context, session sessions.Session)) *AuthInterface_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		var arg1 sessions.Session
		if args[1] != nil {
			arg1 = args[1].(sessions.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthInterface_Logout_Call) Return() *AuthInterface_Logout_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthInterface_Logout_Call) RunAndReturn(run func(context *gin.Context, session sessions.Session)) *AuthInterface_Logout_Call {
	_c.Run(run)
	return _c
}

// NotAuthWithError provides a mock function for the type AuthInterface
func (_mock *AuthInterface) NotAuthWithError(context *gin.Context, s string) {
	_mock.Called(context, s)
	return
}

// AuthInterface_NotAuthWithError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotAuthWithError'
type AuthInterface_NotAuthWithError_Call struct {
	*mock.Call
}

// NotAuthWithError is a helper method to define mock.On call
//   - context *gin.Context
//   - s string
func (_e *AuthInterface_Expecter) NotAuthWithError(context any, s any) *AuthInterface_NotAuthWithError_Call {
	return &AuthInterface_NotAuthWithError_Call{Call: _e.mock.On("NotAuthWithError", context, s)}
}

func (_c *AuthInterface_NotAuthWithError_Call) Run(run func(context *gin.Context, s string)) *AuthInterface_NotAuthWithError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthInterface_NotAuthWithError_Call) Return() *AuthInterface_NotAuthWithError_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthInterface_NotAuthWithError_Call) RunAndReturn(run func(context *gin.Context, s string)) *AuthInterface_NotAuthWithError_Call {
	_c.Run(run)
	return _c
}

// RefreshToken provides a mock function for the type AuthInterface
func (_mock *AuthInterface) RefreshToken(context *gin.Context, session sessions.Session, uACClaims *authenticate.UACClaims) {
	_mock.Called(context, session, uACClaims)
	return
}

// AuthInterface_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type AuthInterface_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - context *gin.Context
//   - session sessions.Session
//   - uACClaims *authenticate.UACClaims
func (_e *AuthInterface_Expecter) RefreshToken(context any, session any, uACClaims any) *AuthInterface_RefreshToken_Call {
	return &AuthInterface_RefreshToken_Call{Call: _e.mock.On("RefreshToken", context, session, uACClaims)}
}

func (_c *AuthInterface_RefreshToken_Call) Run(run func(context *gin.Context, session sessions.Session, uACClaims *authenticate.UACClaims)) *AuthInterface_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		var arg1 sessions.Session
		if args[1] != nil {
			arg1 = args[1].(sessions.Session)
		}
		var arg2 *authenticate.UACClaims
		if args[2] != nil {
			arg2 = args[2].(*authenticate.UACClaims)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthInterface_RefreshToken_Call) Return() *AuthInterface_RefreshToken_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthInterface_RefreshToken_Call) RunAndReturn(run func(context *gin.Context, session sessions.Session, uACClaims *authenticate.UACClaims)) *AuthInterface_RefreshToken_Call {
	_c.Run(run)
	return _c
}
