// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ONSdigital/blaise-cawi-portal/authenticate"
	"github.com/ONSdigital/blaise-cawi-portal/busapi"
	mock "github.com/stretchr/testify/mock"
)

// NewJWTCryptoInterface creates a new instance of JWTCryptoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTCryptoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTCryptoInterface {
	mock := &JWTCryptoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JWTCryptoInterface is an autogenerated mock type for the JWTCryptoInterface type
type JWTCryptoInterface struct {
	mock.Mock
}

type JWTCryptoInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *JWTCryptoInterface) EXPECT() *JWTCryptoInterface_Expecter {
	return &JWTCryptoInterface_Expecter{mock: &_m.Mock}
}

// DecryptJWT provides a mock function for the type JWTCryptoInterface
func (_mock *JWTCryptoInterface) DecryptJWT(ifaceVal interface{}) (*authenticate.UACClaims, error) {
	ret := _mock.Called(ifaceVal)

	if len(ret) == 0 {
		panic("no return value specified for DecryptJWT")
	}

	var r0 *authenticate.UACClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(interface{}) (*authenticate.UACClaims, error)); ok {
		return returnFunc(ifaceVal)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}) *authenticate.UACClaims); ok {
		r0 = returnFunc(ifaceVal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authenticate.UACClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = returnFunc(ifaceVal)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JWTCryptoInterface_DecryptJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptJWT'
type JWTCryptoInterface_DecryptJWT_Call struct {
	*mock.Call
}

// DecryptJWT is a helper method to define mock.On call
//   - ifaceVal interface{}
func (_e *JWTCryptoInterface_Expecter) DecryptJWT(ifaceVal any) *JWTCryptoInterface_DecryptJWT_Call {
	return &JWTCryptoInterface_DecryptJWT_Call{Call: _e.mock.On("DecryptJWT", ifaceVal)}
}

func (_c *JWTCryptoInterface_DecryptJWT_Call) Run(run func(ifaceVal interface{})) *JWTCryptoInterface_DecryptJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JWTCryptoInterface_DecryptJWT_Call) Return(uACClaims *authenticate.UACClaims, err error) *JWTCryptoInterface_DecryptJWT_Call {
	_c.Call.Return(uACClaims, err)
	return _c
}

func (_c *JWTCryptoInterface_DecryptJWT_Call) RunAndReturn(run func(ifaceVal interface{}) (*authenticate.UACClaims, error)) *JWTCryptoInterface_DecryptJWT_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptJWT provides a mock function for the type JWTCryptoInterface
func (_mock *JWTCryptoInterface) EncryptJWT(s string, uACInfo *busapi.UACInfo, n int) (string, error) {
	ret := _mock.Called(s, uACInfo, n)

	if len(ret) == 0 {
		panic("no return value specified for EncryptJWT")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *busapi.UACInfo, int) (string, error)); ok {
		return returnFunc(s, uACInfo, n)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *busapi.UACInfo, int) string); ok {
		r0 = returnFunc(s, uACInfo, n)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, *busapi.UACInfo, int) error); ok {
		r1 = returnFunc(s, uACInfo, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JWTCryptoInterface_EncryptJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptJWT'
type JWTCryptoInterface_EncryptJWT_Call struct {
	*mock.Call
}

// EncryptJWT is a helper method to define mock.On call
//   - s string
//   - uACInfo *busapi.UACInfo
//   - n int
func (_e *JWTCryptoInterface_Expecter) EncryptJWT(s any, uACInfo any, n any) *JWTCryptoInterface_EncryptJWT_Call {
	return &JWTCryptoInterface_EncryptJWT_Call{Call: _e.mock.On("EncryptJWT", s, uACInfo, n)}
}

func (_c *JWTCryptoInterface_EncryptJWT_Call) Run(run func(s string, uACInfo *busapi.UACInfo, n int)) *JWTCryptoInterface_EncryptJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *busapi.UACInfo
		if args[1] != nil {
			arg1 = args[1].(*busapi.UACInfo)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *JWTCryptoInterface_EncryptJWT_Call) Return(s1 string, err error) *JWTCryptoInterface_EncryptJWT_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *JWTCryptoInterface_EncryptJWT_Call) RunAndReturn(run func(s string, uACInfo *busapi.UACInfo, n int) (string, error)) *JWTCryptoInterface_EncryptJWT_Call {
	_c.Call.Return(run)
	return _c
}
