// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewLanguageManagerInterface creates a new instance of LanguageManagerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLanguageManagerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *LanguageManagerInterface {
	mock := &LanguageManagerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LanguageManagerInterface is an autogenerated mock type for the LanguageManagerInterface type
type LanguageManagerInterface struct {
	mock.Mock
}

type LanguageManagerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *LanguageManagerInterface) EXPECT() *LanguageManagerInterface_Expecter {
	return &LanguageManagerInterface_Expecter{mock: &_m.Mock}
}

// IsWelsh provides a mock function for the type LanguageManagerInterface
func (_mock *LanguageManagerInterface) IsWelsh(context *gin.Context) bool {
	ret := _mock.Called(context)

	if len(ret) == 0 {
		panic("no return value specified for IsWelsh")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(*gin.Context) bool); ok {
		r0 = returnFunc(context)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// LanguageManagerInterface_IsWelsh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsWelsh'
type LanguageManagerInterface_IsWelsh_Call struct {
	*mock.Call
}

// IsWelsh is a helper method to define mock.On call
//   - context *gin.Context
func (_e *LanguageManagerInterface_Expecter) IsWelsh(context any) *LanguageManagerInterface_IsWelsh_Call {
	return &LanguageManagerInterface_IsWelsh_Call{Call: _e.mock.On("IsWelsh", context)}
}

func (_c *LanguageManagerInterface_IsWelsh_Call) Run(run func(context *gin.Context)) *LanguageManagerInterface_IsWelsh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *LanguageManagerInterface_IsWelsh_Call) Return(b bool) *LanguageManagerInterface_IsWelsh_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *LanguageManagerInterface_IsWelsh_Call) RunAndReturn(run func(context *gin.Context) bool) *LanguageManagerInterface_IsWelsh_Call {
	_c.Call.Return(run)
	return _c
}

// LanguageError provides a mock function for the type LanguageManagerInterface
func (_mock *LanguageManagerInterface) LanguageError(stringToString map[string]string, context *gin.Context) string {
	ret := _mock.Called(stringToString, context)

	if len(ret) == 0 {
		panic("no return value specified for LanguageError")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(map[string]string, *gin.Context) string); ok {
		r0 = returnFunc(stringToString, context)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// LanguageManagerInterface_LanguageError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LanguageError'
type LanguageManagerInterface_LanguageError_Call struct {
	*mock.Call
}

// LanguageError is a helper method to define mock.On call
//   - stringToString map[string]string
//   - context *gin.Context
func (_e *LanguageManagerInterface_Expecter) LanguageError(stringToString any, context any) *LanguageManagerInterface_LanguageError_Call {
	return &LanguageManagerInterface_LanguageError_Call{Call: _e.mock.On("LanguageError", stringToString, context)}
}

func (_c *LanguageManagerInterface_LanguageError_Call) Run(run func(stringToString map[string]string, context *gin.Context)) *LanguageManagerInterface_LanguageError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]string
		if args[0] != nil {
			arg0 = args[0].(map[string]string)
		}
		var arg1 *gin.Context
		if args[1] != nil {
			arg1 = args[1].(*gin.Context)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LanguageManagerInterface_LanguageError_Call) Return(s string) *LanguageManagerInterface_LanguageError_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *LanguageManagerInterface_LanguageError_Call) RunAndReturn(run func(stringToString map[string]string, context *gin.Context) string) *LanguageManagerInterface_LanguageError_Call {
	_c.Call.Return(run)
	return _c
}

// SetWelsh provides a mock function for the type LanguageManagerInterface
func (_mock *LanguageManagerInterface) SetWelsh(context *gin.Context, b bool) {
	_mock.Called(context, b)
	return
}

// LanguageManagerInterface_SetWelsh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWelsh'
type LanguageManagerInterface_SetWelsh_Call struct {
	*mock.Call
}

// SetWelsh is a helper method to define mock.On call
//   - context *gin.Context
//   - b bool
func (_e *LanguageManagerInterface_Expecter) SetWelsh(context any, b any) *LanguageManagerInterface_SetWelsh_Call {
	return &LanguageManagerInterface_SetWelsh_Call{Call: _e.mock.On("SetWelsh", context, b)}
}

func (_c *LanguageManagerInterface_SetWelsh_Call) Run(run func(context *gin.Context, b bool)) *LanguageManagerInterface_SetWelsh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LanguageManagerInterface_SetWelsh_Call) Return() *LanguageManagerInterface_SetWelsh_Call {
	_c.Call.Return()
	return _c
}

func (_c *LanguageManagerInterface_SetWelsh_Call) RunAndReturn(run func(context *gin.Context, b bool)) *LanguageManagerInterface_SetWelsh_Call {
	_c.Run(run)
	return _c
}
