// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// LoginManagerInterface is an autogenerated mock type for the LoginManagerInterface type
type LoginManagerInterface struct {
	mock.Mock
}

// IsWelsh provides a mock function with given fields: _a0
func (_m *LoginManagerInterface) IsWelsh(_a0 *gin.Context) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*gin.Context) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetWelsh provides a mock function with given fields: _a0, _a1
func (_m *LoginManagerInterface) SetWelsh(_a0 *gin.Context, _a1 bool) {
	_m.Called(_a0, _a1)
}
