// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ONSdigital/blaise-cawi-portal/blaiserestapi"
	mock "github.com/stretchr/testify/mock"
)

// NewBlaiseRestAPIInterface creates a new instance of BlaiseRestAPIInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlaiseRestAPIInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlaiseRestAPIInterface {
	mock := &BlaiseRestAPIInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BlaiseRestAPIInterface is an autogenerated mock type for the BlaiseRestAPIInterface type
type BlaiseRestAPIInterface struct {
	mock.Mock
}

type BlaiseRestAPIInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *BlaiseRestAPIInterface) EXPECT() *BlaiseRestAPIInterface_Expecter {
	return &BlaiseRestAPIInterface_Expecter{mock: &_m.Mock}
}

// GetInstrumentSettings provides a mock function for the type BlaiseRestAPIInterface
func (_mock *BlaiseRestAPIInterface) GetInstrumentSettings(context1 context.Context, s string) (blaiserestapi.InstrumentSettings, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetInstrumentSettings")
	}

	var r0 blaiserestapi.InstrumentSettings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (blaiserestapi.InstrumentSettings, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) blaiserestapi.InstrumentSettings); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(blaiserestapi.InstrumentSettings)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BlaiseRestAPIInterface_GetInstrumentSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstrumentSettings'
type BlaiseRestAPIInterface_GetInstrumentSettings_Call struct {
	*mock.Call
}

// GetInstrumentSettings is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *BlaiseRestAPIInterface_Expecter) GetInstrumentSettings(context1 any, s any) *BlaiseRestAPIInterface_GetInstrumentSettings_Call {
	return &BlaiseRestAPIInterface_GetInstrumentSettings_Call{Call: _e.mock.On("GetInstrumentSettings", context1, s)}
}

func (_c *BlaiseRestAPIInterface_GetInstrumentSettings_Call) Run(run func(context1 context.Context, s string)) *BlaiseRestAPIInterface_GetInstrumentSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BlaiseRestAPIInterface_GetInstrumentSettings_Call) Return(instrumentSettings blaiserestapi.InstrumentSettings, err error) *BlaiseRestAPIInterface_GetInstrumentSettings_Call {
	_c.Call.Return(instrumentSettings, err)
	return _c
}

func (_c *BlaiseRestAPIInterface_GetInstrumentSettings_Call) RunAndReturn(run func(context1 context.Context, s string) (blaiserestapi.InstrumentSettings, error)) *BlaiseRestAPIInterface_GetInstrumentSettings_Call {
	_c.Call.Return(run)
	return _c
}
