// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	busapi "github.com/ONSdigital/blaise-cawi-portal/busapi"
	mock "github.com/stretchr/testify/mock"
)

// BUSAPIInterface is an autogenerated mock type for the BUSAPIInterface type
type BUSAPIInterface struct {
	mock.Mock
}

// GetUACInfo provides a mock function with given fields: _a0
func (_m *BUSAPIInterface) GetUACInfo(_a0 string) (busapi.UACInfo, error) {
	ret := _m.Called(_a0)

	var r0 busapi.UACInfo
	if rf, ok := ret.Get(0).(func(string) busapi.UACInfo); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(busapi.UACInfo)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
