// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ONSdigital/blaise-cawi-portal/busapi"
	mock "github.com/stretchr/testify/mock"
)

// NewBUSAPIInterface creates a new instance of BUSAPIInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBUSAPIInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BUSAPIInterface {
	mock := &BUSAPIInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BUSAPIInterface is an autogenerated mock type for the BUSAPIInterface type
type BUSAPIInterface struct {
	mock.Mock
}

type BUSAPIInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *BUSAPIInterface) EXPECT() *BUSAPIInterface_Expecter {
	return &BUSAPIInterface_Expecter{mock: &_m.Mock}
}

// GetUACInfo provides a mock function for the type BUSAPIInterface
func (_mock *BUSAPIInterface) GetUACInfo(context1 context.Context, s string) (busapi.UACInfo, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetUACInfo")
	}

	var r0 busapi.UACInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (busapi.UACInfo, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) busapi.UACInfo); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(busapi.UACInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BUSAPIInterface_GetUACInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUACInfo'
type BUSAPIInterface_GetUACInfo_Call struct {
	*mock.Call
}

// GetUACInfo is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *BUSAPIInterface_Expecter) GetUACInfo(context1 any, s any) *BUSAPIInterface_GetUACInfo_Call {
	return &BUSAPIInterface_GetUACInfo_Call{Call: _e.mock.On("GetUACInfo", context1, s)}
}

func (_c *BUSAPIInterface_GetUACInfo_Call) Run(run func(context1 context.Context, s string)) *BUSAPIInterface_GetUACInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BUSAPIInterface_GetUACInfo_Call) Return(uACInfo busapi.UACInfo, err error) *BUSAPIInterface_GetUACInfo_Call {
	_c.Call.Return(uACInfo, err)
	return _c
}

func (_c *BUSAPIInterface_GetUACInfo_Call) RunAndReturn(run func(context1 context.Context, s string) (busapi.UACInfo, error)) *BUSAPIInterface_GetUACInfo_Call {
	_c.Call.Return(run)
	return _c
}
